In [ ]:
!pip install img2vec_pytorch

  Created wheel for img2vec-pytorch: filename=img2vec_pytorch-0.2.5-py3-none-any.whl size=4345 sha256=15b943b251f835e1361fa44ff84ff227ac57762570c28b79a2a68b83d710d3f9
  Stored in directory: /root/.cache/pip/wheels/07/4d/bf/9de03c3e76c20899b69498f90624ec499c7c67dd13f183f4e9
Successfully built img2vec-pytorch


In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.model_selection import train_test_split
import random
import os
from img2vec_pytorch import Img2Vec
from PIL import Image
 
# Initialize Img2Vec with GPU
img2vec = Img2Vec(cuda=False)
minmax = MinMaxScaler()
np.random.seed(42)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


  0%|          | 0.00/44.7M [00:00<?, ?B/s]

/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py:310: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  warnings.warn("The use of the transforms.Scale transform is deprecated, " +


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
DATA_DIR = '/content/drive/MyDrive/SignatureDetection/author_data'

In [ ]:
def load_data_vec(DATA_DIR=DATA_DIR, test_size=0.2, verbose=True, load_grayscale=True):
    """
        Loads the data into a dataframe.
        
        Arguments:
            DATA_DIR: str
            test_size: float
        Returns:
            (x_train, y_train,x_test, y_test, df)
    """
    features = []
    features_dict = {}
    labels = [] 
    mode = "rgb"
    count = 1
    if load_grayscale:
        mode = "grayscale"
    
    for folder in os.listdir(DATA_DIR):
  
        if folder == '.DS_Store' or folder == '.ipynb_checkpoints' or folder == 'desktop.ini':
            continue
        print (count, "Searching folder: {}".format(folder))
        for sub in os.listdir(DATA_DIR+"/"+ folder):
            f = DATA_DIR+"/"+ folder +"/"+ sub
            if sub == 'desktop.ini' or sub =='fail' or f == 'desktop.ini':
              continue
            img = load_img(f, color_mode=mode)
            features.append(img2vec.get_vec(img))
            features_dict[sub] = (img, 0)
        
            labels.append(folder)
        count+=1
            
    features = np.array(features)
    features = minmax.fit_transform(features)
    
    Le = LabelEncoder()
    
    labels = np.array(labels)
    #labels = minmax.fit_transform(labels.reshape(-1,1))
    labels_encoder = Le.fit_transform(labels)
 
    x_train, x_test, y_train, y_test = train_test_split(features, labels_encoder, test_size=test_size, random_state=42)
    #x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.25, random_state=42)
    
    print("Find total",count,"folder.")
    print ("Generated data.")
    return features, labels, labels_encoder, features_dict,x_train, x_test, y_train, y_test

In [ ]:
features, labels, labels_encoder, features_dict,x_train, x_test, y_train, y_test = load_data_vec(verbose=False, load_grayscale=False)

55 Searching folder: KoplowMG
56 Searching folder: KennyFW
57 Searching folder: KeaneTM
58 Searching folder: JonesSO
59 Searching folder: JessupHS
60 Searching folder: JarrettJE
61 Searching folder: IdleJR
62 Searching folder: HsiehTC
63 Searching folder: HoytWT
64 Searching folder: HoneycuttDG
65 Searching folder: HolekML
66 Searching folder: HobbsWD
67 Searching folder: HendershotML
68 Searching folder: HeimannRK
69 Searching folder: HattonCR
70 Searching folder: HarrisTC
71 Searching folder: HamannMA
72 Searching folder: HallLM
73 Searching folder: GravelyLE
74 Searching folder: GourleyRD
75 Searching folder: GertenbechRF
76 Searching folder: GertenbachRF
77 Searching folder: GehaRS
78 Searching folder: GaleottiKL
79 Searching folder: FerraroCJ
80 Searching folder: FeldmanJD
81 Searching folder: FassuliotisConstance
82 Searching folder: EisenbergAD
83 Searching folder: DimechEllen
84 Searching folder: DaigleWP
85 Searching folder: CowingMW
86 Searching folder: ColinJan
87 Searching 

In [ ]:
print(len(features))

549


In [ ]:
print(x_train)

[[0.83673984 0.34997338 0.37000564 ... 0.01352965 0.09668132 0.05802956]
 [0.60366464 0.09347636 0.1442512  ... 0.7895495  0.31769943 0.36176488]
 [0.15097974 0.11375149 0.         ... 0.03696065 0.01075013 0.3050281 ]
 ...
 [0.15991092 0.18324366 0.2774019  ... 0.2443763  0.19558877 0.27056527]
 [0.03584806 0.23356113 0.17930956 ... 0.29787126 0.03847598 0.2931704 ]
 [0.08310711 0.21585657 0.22279382 ... 0.34473258 0.02374302 0.33821934]]


In [ ]:
print(labels_encoder)

[ 95  95  95  95  95  95  95  95  95 103 103 103 103 103 103 103  91  91
  91  91  91 102 102  87  87  87  87 100  90  90  90  90  90  90  90  90
  90  98  98  98  98  98  98  98  98  98  98  99  99  92  92  97  85  93
  93  93  86  86  88  88  88  88  89  89  89  89  89  89  89  94  94  94
  94  94  94  94  94  94  94  96  96  96  96  96  96  96 101 101 101 101
 101  84  84  84  84  83  83  83  83  83  83  83  82  82  82  82  81  80
  80  80  80  79  79  79  79  79  79  79  79  78  77  76  76  76  76  76
  75  75  75  74  73  72  71  70  69  69  69  69  69  69  69  68  68  68
  68  68  68  68  68  68  67  67  66  66  66  66  66  66  66  66  66  66
  66  66  65  65  65  65  65  65  65  65  65  65  65  65  65  64  64  63
  63  63  63  63  63  63  63  63  62  62  62  62  62  62  62  62  62  62
  62  61  61  60  59  59  59  58  58  57  56  56  56  56  55  55  55  55
  54  54  53  53  53  53  53  53  53  53  53  53  53  53  53  52  52  52
  52  51  51  51  51  51  51  50  50  50  50  50  5

In [ ]:
print(y_train)

[  9  66 103  33  98  93   2  98  84  10  27  19  13  50   0  22   8  26
  59  33  28  27  39  22  94  49   5  17  63  76  22  53  51  65   2  39
   8  25  47  38  26  38  16  91  25  86   9  44  23  13  49   9  62  87
  43  98  30   4  14  22  38  66  75  43  25  65  90  79  40  65  27  56
  86  49  87  91  51  89  50   3  47  16  13  84  63  52  84  87  46  40
  41  95  79  98  53  38  91  99  21  21  95  47  50  88  62   3  80  15
  40  90  50  53  87  95  63  92  80  98  66   4  79  21  79  41  59  65
  50  25  68  62  19  17  43  39   9   6  68  20  89  18  53  65  62  47
  17  47  62  66   6  28  15  23  82  25  94  29   3  78  38  32  22   3
  34  43  33  17  33  90  69  49  37  88  79  40  14  48  21  67  47  17
  98  27  62  42  68  16  68  17  19  76  19  83  68  51   3  83   8  43
  22  76  63  59  50  14  33  22  17   1  37  76  31  53   9  53  74   6
  35  25   1  35  22  33  43  19  23  30  79  63  30   9   8  38  67   3
  52  39  28  65  38  69  62  49  52  79  77  22  5

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=3, weights = 'distance')

In [ ]:
knn_model.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='distance')

In [ ]:
y_pred = knn_model.predict(x_test)
print(y_pred)

[ 62  90   9  15  13   9  96  26   7  49  63 103  94  53  26  96  25  95
  53  16  23  47  14  65  96  79  63  43  75   7  50  81   6  91  19  94
  42  65  21   8  61  30  28  94  66  63  38   6  44  20  23  87  38  26
  38  93  45  15 101  15  79  51  90  64  82 103  68  22  21 101  68   7
  33  79  90  25  84  68   2  66  94  15  62  89   1  89  52   8  14   6
  15  90  17  63  95 103  46  26  26  83  38 101  34  30  56   1  69  26
  91  37]


In [ ]:
print('accuracy = ', accuracy_score(y_test, y_pred)*100)
#print('precision = ',precision_score(y_test, y_pred)*100)
#print('recall = ',recall_score(y_test, y_pred)*100)
#print('precision = ',precision_score(y_test, y_pred)*100)
#print('f1-score = ',f1_score(y_test, y_pred)*100)
 
print(classification_report(y_test, y_pred))

accuracy =  70.9090909090909
              precision    recall  f1-score   support

           1       1.00      0.67      0.80         3
           2       1.00      0.50      0.67         2
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         2
           6       1.00      1.00      1.00         3
           7       0.67      1.00      0.80         2
           8       1.00      1.00      1.00         2
           9       1.00      0.67      0.80         3
          10       0.00      0.00      0.00         1
          13       1.00      1.00      1.00         1
          14       1.00      1.00      1.00         2
          15       0.60      1.00      0.75         3
          16       1.00      1.00      1.00         1
          17       1.00      1.00      1.00         1
          19       0.00      0.00      0.00         0
          20       0.00      0.00      0.00         0
          21       1.00      1.00      1.00         

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import average_precision_score
average_precision = average_precision_score(y_test, y_pred)
 
print('Average precision-recall score: {0:0.2f}'.format(
      average_precision))

In [ ]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import plot_precision_recall_curve
import matplotlib.pyplot as plt

disp = plot_precision_recall_curve(knn_model, x_test, y_test)
disp.ax_.set_title('2-class Precision-Recall curve: ''AP={0:0.2f}'.format(average_precision))